CreditLineTest/config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  get 'home/index'

  resources :credits
  resources :transactions
  resources :users
  resources :home do
    resources :transactions
    collection do
      post 'drawMoney'
      post 'payMoney'
      get 'calcInterest'
    end
  end

  resources :tests

   root 'home#index'

end

CreditLineTest/app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user
	has_many :transactions

	validates :userId, presence: true
	validates :currLimit, presence: true
	validates :dateUpdated, presence: true
	validates :totalInterest, presence: true
	validates :principal, presence: true

	def self.getCredit(userId)
  		where("userId = '#{userId}'").first
	end

end

CreditLineTest/app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:userId, :currLimit, :dateUpdated, :totalInterest, :principal)
    end
end

CreditLineTest/app/helpers/credits_helper.rb
module CreditsHelper
end

CreditLineTest/app/views/credits/_form.html.erb
<%= form_for @credit do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userId %><br>
    <%= f.text_field :userId %>
  </div>
  <div class="field">
    <%= f.label :currLimit %><br>
    <%= f.text_field :currLimit %>
  </div>
  <div class="field">
    <%= f.label :dateUpdated %><br>
    <%= f.date_select :dateUpdated %>
  </div>
  <div class="field">
    <%= f.label :totalInterest %><br>
    <%= f.text_field :totalInterest %>
  </div>
  <div class="field">
    <%= f.label :principal %><br>
    <%= f.text_field :principal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CreditLineTest/app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

CreditLineTest/app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credits</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Currlimit</th>
      <th>Dateupdated</th>
      <th>Totalinterest</th>
      <th>Principal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.userId %></td>
        <td><%= credit.currLimit %></td>
        <td><%= credit.dateUpdated %></td>
        <td><%= credit.totalInterest %></td>
        <td><%= credit.principal %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

CreditLineTest/app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

CreditLineTest/app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @credit.userId %>
</p>

<p>
  <strong>Currlimit:</strong>
  <%= @credit.currLimit %>
</p>

<p>
  <strong>Dateupdated:</strong>
  <%= @credit.dateUpdated %>
</p>

<p>
  <strong>Totalinterest:</strong>
  <%= @credit.totalInterest %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @credit.principal %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>